### ISSUE TITLE
Allow custom ENV-variables and secrets

### ISSUE THREAD

**Issue by janpieper** [promitor/charts#105]
## Problem

Currently, there is no way to configure custom ENV-variables or secrets for the promitor-agent-scraper deployment:

https://github.com/promitor/charts/blob/bfa0c414efba7e4c85e44bdd9f0206ec36d16566/promitor-agent-scraper/templates/deployment.yaml#L77-L91

As you can see, only two specific ENV-variables can be configured, but no custom ENV-variables :man_shrugging: 

## Context

For example, when using an SAS token for accessing Azure Storage Queues, you can use `sasToken.environmentVariable` (see [docs](http://docs.promitor.io/configuration/v2.x/metrics/storage-queue)) in the metric definition to specify an ENV-variable where to get the SAS token from.

## Possible Solution

It would be great to have optional `deployment.extraEnv` and `secrets.extra` settings, to add custom ENV-variables and/or secrets.

```yaml

deployment:
  extraEnv:
    - name: AZURE_STORAGE_QUEUE_SAS_TOKEN
      valueFrom:
        secretKeyRef:
          name: promitor-agent-scraper
          key: azure-storage-queue-sas-token

secrets:
  extra:
    azure-storage-queue-sas-token: <value>
```
