### ISSUE TITLE
Missing secret name for ENV-variable when not creating secret

### ISSUE THREAD

**Issue by janpieper** [promitor/charts#107]
## Problem

When setting `secrets.createSecret` to `false` and not configuring `secrets.secretName`, the ENV-variable definition for `PROMITOR_AUTH_APPKEY` is missing a secret name.

## Actual Behavior

```yaml
# ...
          env:
          - name: PROMITOR_AUTH_APPKEY
            valueFrom:
              secretKeyRef:
                  name:                        # <------- Missing!
                  key: azure-app-key
# ...
```

## Expected Behavior

I would expect an error because when setting `secrets.createSecret` to `false`, I expect the user to specify a custom secret name via `secrets.secretName`.

## Steps to reproduce

```
helm template promitor ./promitor-agent-scraper --set secrets.createSecret=false
```

## Specifications

  - Version: latest (bfa0c414efba7e4c85e44bdd9f0206ec36d16566)
  - Platform: _irrelevant_
  - Subsystem: _irrelevant_
