### ISSUE TITLE
Extra ENV-variables cause problems when used with default ENV-variables

### ISSUE THREAD

**Issue by janpieper** [promitor/charts#108]
## Expected Behavior

When having a setup that adds default ENV-variables (e.g. `PROMITOR_AUTH_APPKEY`) and you add extra ENV-variables via `deployment.env.extra`, you get an error... :disappointed:

This issue has been introduced by:

* #106

## Actual Behavior

```
Error: YAML parse error on promitor-agent-scraper/templates/deployment.yaml: error converting YAML to JSON: yaml: line 52: did not find expected key
```

## Steps to Reproduce the Problem

```sh
helm template promitor-agent-scraper ./promitor-agent-scraper --values values.yaml
```

## Configuration

**values.yaml:**
```yaml
# ...
azureAuthentication:
  identity:
    key: example

deployment:
  env:
    extra:
      - name: AZURE_STORAGE_QUEUE_SAS_TOKEN
        valueFrom:
          secretKeyRef:
            name: promitor-agent-scraper
            key: azure-storage-queue-sas-token
# ...
```

## Specifications

  - Version: d68826e24eb9c31bc83992e3d956fb8f587552a4
  - Platform: _irrelevant_
  - Subsystem: _irrelevant_
