### ISSUE TITLE
Resource Discovery Helm upgrade fails due to atlassian metric sink

### ISSUE THREAD

**Issue by githubcdr** [promitor/charts#116]
## Expected Behavior

Working helm upgrade

## Actual Behavior

```
Error: UPGRADE FAILED: template: promitor-agent-resource-discovery/templates/deployment.yaml:59:145: executing "promitor-agent-resource-discovery/templates/deployment.yaml" at <.Values.metricSinks.atlassianStatuspage.apiKey>: nil pointer evaluating interface {}.atlassianStatuspage
```

## Steps to Reproduce the Problem

  1. Upgrade fomr 0.7.1 to 0.7.5

## Configuration
Provide insights in the configuration that you are using:
- Configured scraping schedule: 

## Specifications

  - Version: 0.7.5

**Comment by tomkerkhove** [comment]
Would you mind sharing your Helm values/configuration please?

**Comment by githubcdr** [comment]
```
image:
  pullPolicy: IfNotPresent

azureAuthentication:
  identity:
    binding: gery
    id: da4
  mode: UserAssignedManagedIdentity

azureLandscape:
  cloud: Global
  tenantId: 805aa8
  subscriptions:
    - ae

cache:
  enabled: true
  durationInMinutes: 6

resources:
  limits:
   cpu: 100m
   memory: 128Mi
  requests:
   cpu: 100m
   memory: 128Mi

rbac:
  ## If true, create & use RBAC resources
  create: true

  ## If true, create & use Pod Security Policy resources
  ## ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/
  podSecurityPolicyEnabled: true

  ## Service Account for pods
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
  serviceAccount:
    ## Specifies whether a service account should be created
    create: true

    ## The name of the service account to use if create is false
    ## If create is true, a name is generated using the fullname template
    name: promitor-resource-discovery

prometheus:
  enabled: true
  enableServiceDiscovery: true
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus-operator
    interval: 60s
    timeout: 10s
## promitor-resource-discovery configuration for sauron environment
## This file inherit from values.common.yaml
## Ref: https://github.com/promitor/charts/tree/main/promitor-agent-resource-discovery

resourceDiscoveryGroups:
  - name: container-registry-landscape
    type: ContainerRegistry
    criteria:
      include:
        subscriptions:
          - aea708c
        resourceGroups:
          - am
```
