### ISSUE TITLE
BadRequest query of Resource Discovery to Azure Resource Graph Explorer (inversion of order and project clauses)

### ISSUE THREAD

**Issue by tgaliotto** [promitor/charts#152]
When I try to run the resource Discovery, I receive following error. 

[13:50:01 WRN] {"DependencyId": null, "DependencyType": "Azure Resource Graph", "DependencyName": "Query", "DependencyData": "Resources\n| where type =~ 'microsoft.storage/storageaccounts'\n| where subscriptionId =~ '07ed8a1a-ceb8-4569-b764-2327d61aaeb2'\n| project subscriptionId, resourceGroup, type, name\n| order by subscriptionId asc, resourceGroup asc, type asc, name asc", "TargetName": "Query", "ResultCode": null, "IsSuccessful": false, "StartTime": "2023-06-23T13:50:01.0386967 +00:00", "Duration": "00:00:00.0777363", "Context": {"Query": "Resources\n| where type =~ 'microsoft.storage/storageaccounts'\n| where subscriptionId =~ '07ed8a1a-ceb8-4569-b764-2327d61aaeb2'\n| project subscriptionId, resourceGroup, type, name\n| order by subscriptionId asc, resourceGroup asc, type asc, name asc", "QueryName": "StorageAccount_Discovery_Group", "TelemetryType": "Dependency"}, "$type": "DependencyLogEntry"}

## Expected query 
Resources
| where type =~ 'microsoft.storage/storageaccounts'
| where subscriptionId =~ '07ed8a1a-ceb8-4569-b764-2327d61aaeb2'
| order by subscriptionId asc, resourceGroup asc, type asc, name asc
| project subscriptionId, resourceGroup, type, name

## Actual Query
Resources 
where type =~ 'microsoft.storage/storageaccounts' 
where subscriptionId =~ '07ed8a1a-ceb8-4569-b764-2327d61aaeb2' 
project subscriptionId, resourceGroup, type, name 
order by subscriptionId asc, resourceGroup asc, type asc, name asc

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Configuration
Provide insights in the configuration that you are using:
- Configured scraping schedule: 

<details>
<summary>Discovery config</summary>

```yaml
  - name: StorageAccount_Discovery_Group
    type: StorageAccount
    criteria:
      include:
        subscriptions:
        - XXX
```
<summary>Agent scraper config</summary>
 
```yaml
  metrics: 
  - name: azure_storage_account_capacity_discovery
    description: "The average capacity used in the storage account"
    resourceType: StorageAccount
    azureMetricConfiguration:
      metricName: UsedCapacity
      aggregation:
        type: Average
    resourceDiscoveryGroups:
    - name: StorageAccount_Discovery_Group
```  
</details>

## Specifications

  - Version: 0.9.1
  - Platform: Kubernetes 1.26.3
