### ISSUE TITLE
Can't leave azureAuthentication.identity.key blank when using your own secrets (secrets.createSecret: false)

### ISSUE THREAD

**Issue by TimDurward** [promitor/charts#48]
Can't leave azureAuthentication.identity.key blank when using your own secrets (secrets.createSecret: false)

## Expected Behavior
When bringing your own service principal secrets, `secrets.createSecret: false` should not require you to use a placeholder for `azureAuthentication.identity.key`. 

## Actual Behavior
If you're using your own secrets you need to put a placeholder for `azureAuthentication.identity.key` otherwise env `PROMITOR_AUTH_APPKEY` will not be templated , for example:
```yaml
  azureAuthentication:
    identity:
      mode: ServicePrincipal
      id: "asdasd"
      # Hack to enable add "PROMITOR_AUTH_APPKEY" env template.
      # https://github.com/promitor/charts/blob/main/promitor-agent-scraper/templates/deployment.yaml#L61-L67
      key: "nil"
  secrets:
    # Bring our own secret
    createSecret: false
    # Name of secret
    secretName: azure-aad-service-principal
    appKeySecret: azure-app-key
```

## Versions
Charts and  versions: 
```yaml
- name: promitor-agent-scraper
  version: "2.4.1"
  repository: "https://charts.promitor.io"
  condition: promitor-agent-scraper.enabled
- name: promitor-agent-resource-discovery
  version: "0.4.1"
  repository: "https://charts.promitor.io"
```

**Comment by TimDurward** [comment]
I suggest adding a third variable for deciding to template the `PROMITOR_AUTH_APPKEY` [env-var](https://github.com/promitor/charts/blob/main/promitor-agent-scraper/templates/deployment.yaml#L61-L67).

Could re-use an existing helm var. ` .Values.secrets.createSecret`.
```yaml
{{- if or .Values.azureAuthentication.identity.key .Values.azureAuthentication.appKey .Values.secrets.createSecret }}

...

{{- end}}
```

**Comment by tomkerkhove** [comment]
Thanks for raising and proposing, are you willing to contribute this?

**Comment by TimDurward** [comment]
I pull in promitor as a helm dependency in my infra/monitoring stack, and ship SealedSecrets alongside them.

Using the below config seems to work just fine, it finds the custom secret that I've installed (`azure-aad-service-principal`). 
```yaml
  azureAuthentication:
    identity:
      mode: ServicePrincipal
      id: "asdasd"
      # Hack to enable add "PROMITOR_AUTH_APPKEY" env template.
      # https://github.com/promitor/charts/blob/main/promitor-agent-scraper/templates/deployment.yaml#L61-L67
      key: "nil"
  secrets:
    # Bring our own secret
    createSecret: false
    # Name of secret
    secretName: azure-aad-service-principal
    appKeySecret: azure-app-key
```

The templating logic to decide if you're using your own custom secrets is here:
https://github.com/promitor/charts/blob/main/promitor-agent-scraper/templates/_helpers.tpl#L55-L63
