### ISSUE TITLE
Security hardening of promitor-agent-scraper

### ISSUE THREAD

**Issue by akostic-kostile** [promitor/charts#69]
In August 2021. NSA and CISA published a [paper](https://www.nsa.gov/Press-Room/News-Highlights/Article/Article/2716980/nsa-cisa-release-kubernetes-hardening-guidance/) on hardering Kubernetes infrastructure and applications. Very soon after that a [tool](https://github.com/armosec/kubescape) was created that scans the cluster and checks if the guildlines are being followed.

I've been doing this hardening for the company I work with, among other things we use promitor-agent-scraper, and I noticed that default settings are extremely lax. Good thing is most of these suggestions can be implemented just by updating the Helm chart, my suggestion would be something like this:

```
kind: Deployment
spec:
  template:
    spec:
      containers:
      - name: promitor-agent-scraper
        securityContext:
          allowPrivilegeEscalation: false # default is false, just making it explicit so users are aware
          capabilities:
            drop:
            - ALL
          privileged: false # default is false, just making it explicit so users are aware
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: tmp
          path: /tmp # dotnet is trying to write temp data here, necessary for readOnlyRootFilesystem=true
      securityContext:
        runAsGroup: 10000
        runAsNonRoot: true
        runAsUser: 10000
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - emptyDir: {}
        name: tmp
```

We run a lot of dotnet where I work, and all of our pods are configured this way. There are a few issues with promitor-agent-scrapper image tho, I tested it with user/group of 10000 and it does not work, Kestrel is trying to bind to ports <1024, and only root or someone with CAP_NET_BIND can do that. Which brings me to my questions:

1) Would you be open to setting the port to something > 1024? We use port 5000. Then a non root user could be used.

2) Would you be open to me creating a pull request to update the Helm chart with these suggestions ?
