### ISSUE TITLE
Support Prometheus Operator in Helm chart

### ISSUE THREAD

**Issue by tomkerkhove** [promitor/charts#7]
> The chart should (optionally) create a ServiceMonitor object so it can seamlessly be integrated into a Prometheus Operator deployment.
> 
> Some examples can be found here:
> - https://github.com/helm/charts/blob/master/stable/prometheus-postgres-exporter/templates/servicemonitor.yaml
> - https://github.com/helm/charts/blob/master/stable/prometheus-redis-exporter/templates/servicemonitor.yaml
> - https://github.com/helm/charts/blob/master/stable/prometheus-rabbitmq-exporter/templates/servicemonitor.yaml

Originally requested by @DaveOHenry in https://github.com/tomkerkhove/promitor/issues/885

**Comment by DaveOHenry** [comment]
I'd still like to see the ServiceMonitor and PrometheusRule features in the chart :-)
https://github.com/DaveOHenry/charts-1/blob/main/promitor-agent-scraper/values.yaml#L18-L56

I'm currently struggling to find a good way of exposing the configuration, because some time ago it was refactored and now includes the "metricSinks" concept. This is certainly a good idea, but where should the parameters for supporting Prometheus Operator go now?
I can imagine that it would be fine for the "ServiceMonitor" configuration to reside at ```metricSinks.prometheusOperator.serviceMonitor``` , but this approach would not make sense for the "PrometheusRule" feature (```metricSinks.prometheusOperator.prometheusRule```) . Maybe a separate section on the root level like ```prometheusOperator``` would be better?

**Comment by tomkerkhove** [comment]
Frankly, the operator & ServiceMonitor is new to me so might ask a stupid question, but why doesn't it make sense for PrometheusRule? Because for the rest it could be part of the `metricSinks` indeed.

**Comment by tomkerkhove** [comment]
Thanks for considering to contribute it btw!

**Comment by DaveOHenry** [comment]
A ServiceMonitor object is just the Prometheus Operator way of automatically discovering how to scrape an application so it would make perfect sense to have it under ```metricSinks``` section.

A PrometheusRule object is a separate Prometheus Operator feature to declaratively describe Prometheus rules. Maybe it's just me, but having Prometheus rules also under the ```metricSinks``` section looks a little bit strange, because these objects describe alerting / recording rules and are therefore not really part of the "metricSinks" concept. 

Keeping the config flat is always a good idea so maybe we should leave the "ServiceMonitor configuration under ```metricSinks``` and have a separate ```prometheusRule``` section on the root level of the configuration?

```
metricSinks:
  prometheusScrapingEndpoint:
    enabled: true
    baseUriPath: /metrics
    enableMetricTimestamps: true
    metricUnavailableValue: NaN
    enableServiceDiscovery: true
    serviceMonitor:
      enabled: false
      namespace: ""
      labels: {}
      interval: 60s
      timeout: 10s
prometheusRule:
  enabled: false
  namespace: ""
  additionalLabels: {}
  rules: []
```
